//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.OpenTMSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL", ConfigurationName="OpenTMSServiceReference.PortType")]
    public interface PortType {
        
        // CODEGEN: Generating message contract since the operation WcShipmentService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/001802.O_USShippingPaper-WERCS.NET_TMSNAM_WCShipment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Service.OpenTMSServiceReference.WcShipmentServiceResponse WcShipmentService(Service.OpenTMSServiceReference.WcShipmentServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/001802.O_USShippingPaper-WERCS.NET_TMSNAM_WCShipment", ReplyAction="*")]
        System.Threading.Tasks.Task<Service.OpenTMSServiceReference.WcShipmentServiceResponse> WcShipmentServiceAsync(Service.OpenTMSServiceReference.WcShipmentServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tMSShipmentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TMSShipmentId {
            get {
                return this.tMSShipmentIdField;
            }
            set {
                this.tMSShipmentIdField = value;
                this.RaisePropertyChanged("TMSShipmentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL")]
    public partial class OpenTMSShipmentTMSShipmentID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OpenTMSShipmentTMSShipmentIDShipmentStop[] shipmentStopField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentStop", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OpenTMSShipmentTMSShipmentIDShipmentStop[] ShipmentStop {
            get {
                return this.shipmentStopField;
            }
            set {
                this.shipmentStopField = value;
                this.RaisePropertyChanged("ShipmentStop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL")]
    public partial class OpenTMSShipmentTMSShipmentIDShipmentStop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string districtField;
        
        private string sourceField;
        
        private string destinationField;
        
        private string createdByField;
        
        private short stopIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short stopId {
            get {
                return this.stopIdField;
            }
            set {
                this.stopIdField = value;
                this.RaisePropertyChanged("stopId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WcShipmentServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL", Order=0)]
        public Service.OpenTMSServiceReference.Request Request;
        
        public WcShipmentServiceRequest() {
        }
        
        public WcShipmentServiceRequest(Service.OpenTMSServiceReference.Request Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WcShipmentServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.slb.com/SIMS/prjBroker_005_aa/WCShipmentServiceWSDL", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TMSShipmentID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Service.OpenTMSServiceReference.OpenTMSShipmentTMSShipmentID[] OpenTMSShipment;
        
        public WcShipmentServiceResponse() {
        }
        
        public WcShipmentServiceResponse(Service.OpenTMSServiceReference.OpenTMSShipmentTMSShipmentID[] OpenTMSShipment) {
            this.OpenTMSShipment = OpenTMSShipment;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortTypeChannel : Service.OpenTMSServiceReference.PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortTypeClient : System.ServiceModel.ClientBase<Service.OpenTMSServiceReference.PortType>, Service.OpenTMSServiceReference.PortType {
        
        public PortTypeClient() {
        }
        
        public PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.OpenTMSServiceReference.WcShipmentServiceResponse Service.OpenTMSServiceReference.PortType.WcShipmentService(Service.OpenTMSServiceReference.WcShipmentServiceRequest request) {
            return base.Channel.WcShipmentService(request);
        }
        
        public Service.OpenTMSServiceReference.OpenTMSShipmentTMSShipmentID[] WcShipmentService(Service.OpenTMSServiceReference.Request Request) {
            Service.OpenTMSServiceReference.WcShipmentServiceRequest inValue = new Service.OpenTMSServiceReference.WcShipmentServiceRequest();
            inValue.Request = Request;
            Service.OpenTMSServiceReference.WcShipmentServiceResponse retVal = ((Service.OpenTMSServiceReference.PortType)(this)).WcShipmentService(inValue);
            return retVal.OpenTMSShipment;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service.OpenTMSServiceReference.WcShipmentServiceResponse> Service.OpenTMSServiceReference.PortType.WcShipmentServiceAsync(Service.OpenTMSServiceReference.WcShipmentServiceRequest request) {
            return base.Channel.WcShipmentServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service.OpenTMSServiceReference.WcShipmentServiceResponse> WcShipmentServiceAsync(Service.OpenTMSServiceReference.Request Request) {
            Service.OpenTMSServiceReference.WcShipmentServiceRequest inValue = new Service.OpenTMSServiceReference.WcShipmentServiceRequest();
            inValue.Request = Request;
            return ((Service.OpenTMSServiceReference.PortType)(this)).WcShipmentServiceAsync(inValue);
        }
    }
}
